language: php

# Add php version so composer doesn't complain
php:
  - 7.1

services:
  - docker

env:
  - DRUPAL_ROOT=/var/www/html

before_script:
  - docker pull statonlab/tripal3

script:
  - docker run -it -d --rm --name tripal -v "$(pwd)":/modules/analyzedphenotypes statonlab/tripal3
  - sleep 30 # We pause here so postgres and apache complete booting up
  - docker exec -it tripal drush pm-download dragndrop_upload
  - docker exec -it tripal bash -c "cd /var/www/html/sites/all/modules && git clone https://github.com/tripal/trpdownload_api.git"
  - docker exec -it tripal bash -c "cd /var/www/html/sites/all/libraries && git clone https://github.com/SystemDevil/PHP_XLSXWriter_plus"
  - docker exec -it tripal bash -c "cd /var/www/html/sites/all/libraries && wget https://github.com/d3/d3/releases/download/v3.5.14/d3.zip && unzip d3.zip"
  - docker exec -it tripal bash -c "cd /var/www/html/sites/all/libraries && mkdir d3 && mv d3.js d3/ && mv d3.min.js d3/"
  - docker exec -it tripal drush pm-enable -y analyzedphenotypes
  - docker exec -it tripal bash -c "cd /modules/analyzedphenotypes && composer install && DRUPAL_ROOT=/var/www/html ./vendor/bin/phpunit"
