language: php

# Add php version so composer doesn't complain
php:
  - 7.1

services:
  - docker

env:
  - DRUPAL_ROOT=/var/www/html IS_TRAVIS=TRUE CC_TEST_REPORTER_ID=754504076c31254876f5d89291dfbb722d2751f0ef72a0161b08f873f1146f2b

before_script:
  - docker pull statonlab/tripal3
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build --debug
  - GIT_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH
  - GIT_COMMIT_SHA=$TRAVIS_PULL_REQUEST_SHA
  - composer global require drupal/coder
  - composer global require drupal/coder:^8.3.1
  - composer global require dealerdirect/phpcodesniffer-composer-installer

script:
  - docker run -it -d --rm --name tripal -v "$(pwd)":/modules/analyzedphenotypes statonlab/tripal3
  - sleep 30 # We pause here so postgres and apache complete booting up
  - docker exec -it tripal drush pm-download dragndrop_upload
  - docker exec -it tripal bash -c "cd /var/www/html/sites/all/modules && git clone https://github.com/tripal/trpdownload_api.git"
  - docker exec -it tripal bash -c "cd /var/www/html/sites/all/modules && git clone https://github.com/tripal/tripald3.git"
  - docker exec -it tripal bash -c "cd /var/www/html/sites/all/libraries && git clone https://github.com/SystemDevil/PHP_XLSXWriter_plus"
  - docker exec -it tripal bash -c "cd /var/www/html/sites/all/libraries && wget https://github.com/d3/d3/releases/download/v3.5.14/d3.zip && unzip d3.zip"
  - docker exec -it tripal bash -c "cd /var/www/html/sites/all/libraries && mkdir d3 && mv d3.js d3/ && mv d3.min.js d3/"
  - docker exec -it tripal drush pm-enable -y analyzedphenotypes
  - docker exec -it tripal yum install -y php-pecl-xdebug.x86_64
  - docker exec -it tripal bash -c "cd /modules/analyzedphenotypes && composer install && DRUPAL_ROOT=/var/www/html ./vendor/bin/phpunit --coverage-clover ./clover.xml"

after_script:
  - ./cc-test-reporter after-build clover.xml --debug -t clover -p /var/www/html/sites/all/modules/custom/analyzedphenotypes --exit-code $TRAVIS_TEST_RESULT
