<?php

/**
 * @file
 * The main functionality of this module.
 */


/**
 * Implements hook_menu().
 */
function analyzedphenotypes_menu() {
  $items = array();

  // ADMINISTRATIVE PAGES.
  $tripal_extension_basepath = 'admin/tripal/extension/';

  // Main administrative pages for analyzed phenotypes.
  $items[$tripal_extension_basepath . 'analyzedphenotypes'] = array(
    'title' => 'Analyzed Phenotypes',
    'description' => 'Lorem ipsum dolor sit amet (Hello Analyzedphenotypes).',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('analyzedphenotypes_admin_page_directory'),
    'access arguments' => array('access administration pages'),
    'file' => 'include/analyzedphenotypes.admin.form.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  // Data Loader.
  $items[$tripal_extension_basepath . 'analyzedphenotypes/data_loader'] = array(
    'title' => 'Analyzed Phenotypes Data Loader',
    'description' => 'Lorem Ipsum dolor sit amet.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('analyzedphenotypes_admin_data_loader'),
    'access arguments' => array('access administration pages'),
    'file' => 'include/analyzedphenotypes.admin.form.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
  );

  // Autocomplete search path.
  $items[$tripal_extension_basepath . 'analyzedphenotypes/autocompletesearch/%'] = array(
    'page callback' => 'analyzedphenotypes_autocomplete_search',
    'page arguments' => array(5),
    'access arguments' => array('access administration pages'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}


module_load_include('inc', 'analyzedphenotypes', 'include/analyzedphenotypes.functions');


/**
 * Implements hook_theme().
 */
function analyzedphenotypes_theme($existing, $type, $theme, $path) {
  $items = array();

  // Administrative page directory
  $items['analyzedphenotypes_admin_page_directory'] = array(
    'render element' => 'form',
    'template' => 'analyzedphenotypes_pages',
    'path' => $path . '/theme',
  );

  // Data loader.
  $items['analyzedphenotypes_admin_data_loader'] = array(
    'render element' => 'form',
    'template' => 'analyzedphenotypes_pages',
    'path' => $path . '/theme',
  );


  return $items;
}



/**
 * Implements hook_libraries_info().
 */
function analyzedphenotypes_libraries_info() {


}


/**
 * Function callback: Fetch records and populate to autocomplete search fields.
 *
 * @param $data_type
 *   A string indicating the source of call and what type of data is requested.
 *   eg. Projects, ontology etc.
 *
 * @return
 *   A JSON object.
 */
function analyzedphenotypes_autocomplete_search($datatype, $key = '') {
  switch($datatype) {
    case 'projects':
      $arr_data = analyzedphenotypes_project_properties('project_pattern_match_name', $key);
      break;
  }

  drupal_json_output($arr_data);
}
